### ISSUE TITLE
Bug: Flicker on tabs with lazy loading

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1053]
**Describe the bug**
In our setup the Tabs component has a flicker when switching between tabs.
(Maybe) Relevant:
* using lazy loading (ng-template)
* rather large dom
* happens as well without Perfect Scrollbar
* workaround:  `sbbTabsAnimations.translateTab.definitions = [];` in `AppModule`

Video/Gif (0.5 speed):
![tabs-flicker](https://user-images.githubusercontent.com/117919/149971409-639a13c9-e89b-43fd-b206-b39ee159ba73.gif)

**To Reproduce**

Provide a reproduction with StackBlitz (e.g. use the StackBlitz buttons on the examples).

**Expected behavior**
After the initial rendering, there should not be an additional flicker.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome
 - Version SACL 13.0.0

**Comment by jeripeierSBB** [comment]
Some of the findings
 - Changing position relative to static in cargo hub ui css overwrites makes the animation impossible to look good
 - Defining the selectedIndex of the tab group happens too late so there is always an animation visible from tab 0 to 1. It could help to make the ViewChild static and setting the index at an earlier moment.

As discussed with @daniel-sc and @kyubisation we will close this issue due to complexity of this case. Anyways, we will provide an input which lets configure the animation duration. If setting the animation duration to 0, the flickering shouldn't happen.
