### ISSUE TITLE
Bug: Radio-Group strange postion

### ISSUE THREAD

**Issue by pavelTre** [sbb-design-systems/sbb-angular#1297]
**Describe the bug**
If the Radio-Group is enclosed by a `<fieldset> `with a `<legend> `there is a strange behavior. The panel is not displayed at the expected position,  it is displayed next to the fieldset.

**To Reproduce**
1. Go [Stackblitz](https://stackblitz.com/edit/angular-cbwab4?file=src%2Fapp%2Fradio-button-panel-content-example.html)
2. See result

**Expected behavior**
The Radio-Group is displayed under the legend.

**Screenshots**
![Screenshot (16)_LI](https://user-images.githubusercontent.com/101404239/158584677-4dcf4878-e5c4-4b82-abc5-07ea9f000575.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BrowserChrome

**Additional context**
A workaround to fix this problem is to add a whitspace `<div>&nbsp;</div>` after the `legend`-tag.

**Comment by pavelTre** [comment]
Hey @jeripeierSBB 
Is it possible to rebuild the styling so that the fix works even if the radio-button-panel is in its own Angular Component and this Compoentn is enclosed by a fieldset with a legend?

See [Stackblitz](https://stackblitz.com/edit/angular-4ymvxf?file=src%2Findex.html)

**Comment by jeripeierSBB** [comment]
Hello @pavelTre , due to browser default styles which are a little bit special in the case of fieldset legend we seem not able to further improve our solution. But in your case you just need to apply a display style other than inline to your `sbb-radio-button-panel-content-example` element in your example and then it works. Would that solution be acceptable for you?
