### ISSUE TITLE
Feature request: Angular 14 Support

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#1497]
Hello all

As you probably know, Angular 14 was released a few days ago.
Over the last few (major) updates, it sometimes took a lot of effort to migrate because of certain changes in the library (icons, components that are replaced, etc).

This is why I'm currently trying to plan our team's migration to Angular 14 - now the question: Do you already know when Angular 14 support will be added? Maybe also what breaking changes will be introduced?

Sorry if this is already described in an other issue - I couldn't find it. Thanks in advance.

**Comment by sandrooco** [comment]
Also, thanks for always keeping the library up to date with Angular versions. 🎉

**Comment by jeripeierSBB** [comment]
Hi @sandrooco 

Thanks for asking, with v14 there are little changes and very little breaking changes. Probably the only thing you have to change manually, is, if you use our library styles in your sass files (eg. variables or mixins). With v14 you have to use `@use` instead of `@import`. For this change we cannot provide an automatic migration and therefore some changes have to be made by you.

We are planning to release v14 this week.

I hope this answers your questions.

**Comment by sandrooco** [comment]
Yes, it does answer my question. Thank you.
Regarding styling (not in Angular 14 context): do you plan to fully switch to css variables at some point in the near future?

**Comment by jeripeierSBB** [comment]
What do you mean with "fully" switch? Like every value should be in a variable?

**Comment by sandrooco** [comment]
Yes - or at least most. 😅 I saw that colors are exposed as css variables already.
It's great for build optimization because files are more independent and tree shaking works even better (no @import or @use).

**Comment by kyubisation** [comment]
We already have quite a bit of variables at the moment: https://github.com/sbb-design-systems/sbb-angular/blob/main/src/angular/styles/_typography.scss#L48-L525
We are considering extending this further, but this will be at the earliest for v15 in autumn.

**Comment by sandrooco** [comment]
Nice, thanks!
