### ISSUE TITLE
[Bug]: Badge on sbb-icon not displayed correctly

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#2225]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.2.2

### Operating system

Win10

### Browser / Browser version

Chrome 123 / Firefox stable

### Input mode

None

### What happened?

When using the "badge" component on the "icon" component and conditionally rendering the icon with ngIf, the bage is displayed above the icon. It is expected that the badge is displayed next to the icon

### Steps to reproduce the issue

1. Open https://stackblitz.com/edit/kpecgz?file=src%2Fapp%2Fbadge-overview-example.ts
2. Click on "Toggle Badge"
3. Observe that the badges on the icons are displayed differently. Green bell: wrong, red bell: correct.

<img width="205" alt="image" src="https://github.com/sbb-design-systems/sbb-angular/assets/117919/b3109ea9-fc61-4761-b1aa-456ef9afc3bb">

**Comment by mhaertwig** [comment]
Thanks for the bug report!

After looking at the code I am pretty sure that the green badge is positioned correctly. Alternatively, when setting `sbbBadgePosition` to `after`, it should look like this: 
![image](https://github.com/sbb-design-systems/sbb-angular/assets/3184240/29dfabad-69c6-4c21-bda5-36bd5be8c0ec)

The badge element is always appended to the parent element (see [this line of code](https://github.com/angular/components/blob/main/src/material/badge/badge.ts#L267)). Since the icon is loaded from the CDN, the parent element is empty at the time this code is executed. Later, the icon is added _after_ the badge.

@mcilurzo, is there a design specification how badges should be positioned on icons? 

Moreover, in my opinion the positioning does not work as expected. We'll discuss this internally.

**Comment by daniel-sc** [comment]
@mhaertwig the actual position is not as important as consistency from my point of view. Ideally, DOM elements have the same structure in both scenarios.

**Comment by mhaertwig** [comment]
@daniel-sc, thanks for the feedback. I wrote the previous comment primary for the documentation of my analysis. I'll discuss everything internally and provide a solution as soon as possible.

**Comment by kyubisation** [comment]
Hello @daniel-sc 
We have discussed this, but not yet found a solid solution. @mhaertwig is currently on vacation and will be back in two weeks.

**Comment by mhaertwig** [comment]
@daniel-sc I am back from vacation and we're working on a fix. There'll be a release with the fix within the next two weeks.
