### ISSUE TITLE
[Bug]: <sbb-error> not working with <sbb-chip-list>

### ISSUE THREAD

**Issue by 0x49b** [sbb-design-systems/sbb-angular#2244]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.8.1

### Operating system

macOS

### Browser / Browser version

Safari, Firefox, Brave

### Input mode

Mouse/Keyboard

### Additional settings

-

### What happened?

When using the <sbb-error> inside a <sbb-chip-list> on errors the border of the input gets highlighted in red, but the error strings are not getting displayed. The sbb-form-field-error-wrapper is added, but always empty. 
![image](https://github.com/sbb-design-systems/sbb-angular/assets/2895704/72e56c7b-8ea2-41f9-9064-101daf7c8bdd)I've composed a Stackblitz Example for it, find it here: https://stackblitz.com/edit/wlvyfp-9xdchz

### Steps to reproduce the issue

1. Open Stackblitz Link, execute the Stackblitz if not already running
2. in the input, add a Chip with a number eg. 0815
3. now unfocus the input: red border, but no sbb-error 

### Relevant log output

```shell
No output in console
```

**Comment by mhaertwig** [comment]
The StackBlitz example didn't work because:
* The error was read from the wrong control (`fruitInputCtrl.hasError('pattern')` instead of `selectedFruits.hasError('pattern')`)
* The `<sbb-error />` elements were placed inside the `<sbb-autocomplete />` element instead of the `sbb-form-field` element.

The following example works: https://stackblitz.com/edit/wlvyfp-klr3ws?file=src%2Fapp%2Fchips-autocomplete-example.html,src%2Fapp%2Fchips-autocomplete-example.ts

Since I cannot confirm it's a bug in SBB Anguar, I am closing this issue. Feel free to re-open if you don't agree.
