### ISSUE TITLE
[Bug]: Autocomplete element is not highlighted when set through code

### ISSUE THREAD

**Issue by cetide** [sbb-design-systems/sbb-angular#2285]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.8.2

### Operating system

Windows 10

### Browser / Browser version

Google Chrome Version 125.0.6422.114 (64-Bit)

### Input mode

Mouse/Keyboard

### What happened?

We use the autocomplete component with reactive forms, objects and displayWith. When we set the value of the reactive form control in code the related element in the autocomplete component doesn't get highlighted initially. Only after the user reselects the same element through the UI it works.

I tried to use an unique tracking value which didn't help:
@for (option of filteredNodes | slice: 0 : maxDisplayedOptions; track option.absolutNodePath)

I also tried to find the related element in the element list and set the form control value with it which didn't help either:

<img width="304" alt="image" src="https://github.com/sbb-design-systems/sbb-angular/assets/84315780/dbac9990-b609-4e6d-bd8e-73e4f422644a">

Implementation of the autocomplete component in our app:
https://code.sbb.ch/projects/AMN_ISSB/repos/sam-frontend-web/browse/src/app/libs/components/tree-autocomplete/component

Live example in our app:
https://samweb-test.sbb-cloud.net/de/abweichungen?processId=A-432961

### Steps to reproduce the issue

1. Implement the autocomplete like shown in the official example "Autocomplete Display With"
2. Try to set the form control value in code
4. Observe that the set element is not highlighted in the autocomplete options

Example: https://stackblitz.com/edit/yijjqc?file=src%2Fapp%2Fautocomplete-display-with-example.ts

**Comment by mhaertwig** [comment]
Hello @cetide

After discussing your issue internally, we came to the following conclusion: From our perspective it makes more sense if the library keeps highlighting the initially selected value from the `FormControl` instead of selecting it. Otherwise this may lead to inconsistent behavior, e.g. if used in combination with the `filteredOptions` parameter.

However, you can select the option in your code by calling the `select()` method of the `SbbOption`. I've updated your StackBlitz example: https://stackblitz.com/edit/yijjqc-rwuqsz?file=src%2Fapp%2Fautocomplete-display-with-example.ts,src%2Fapp%2Fautocomplete-display-with-example.html

I am closing your bug report. If you don't agree with the suggested solution, please feel free to re-open it or contact me via Teams. 

Regards, Mario
