### ISSUE TITLE
Feature request: Provide IconTestingModule for Angular testsuits

### ISSUE THREAD

**Issue by mischahaenen** [sbb-design-systems/sbb-angular#245]
**Is your feature request related to a problem? Please describe.**
I fixed the angular unit tests for the developer portal and I noticed that it is hard to import all icon modules in every unit test.

**Describe the solution you'd like**
Can you provide an IconTestingModule in the library to mock these Icon-Modules?

**Describe alternatives you've considered**
In this IconTestingModule, could be a set of all icons with no template.

**Comment by kyubisation** [comment]
My recommendation would be to create a shared icon module, which imports/exports all required icons.
Currently there also exists the `IconCollectionModule`, which contains all icons. However I'm a bit worried about the collection modules, since their usage has potentially severe consequences.

I'll leave this issue open, as I might come back to it.

**Comment by jeripeierSBB** [comment]
@kyubisation I think we can close this issue as the angular-icons library is deprecated?

**Comment by kyubisation** [comment]
Yes, with the approaching removal of the @sbb-esta/angular-icons module, this is no longer relevant.
