### ISSUE TITLE
Bug: Pagination cuts off large numbers

### ISSUE THREAD

**Issue by hesyar** [sbb-design-systems/sbb-angular#435]
Pagination with large numbers cuts text off

**To Reproduce**
1. Use large numbers in pagination

**Expected behavior**
Pagination should expand accordingly

**Screenshots**
![image](https://user-images.githubusercontent.com/35898/82896660-a0ae4200-9f56-11ea-9e41-dbedcca2f676.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 83

**Comment by kyubisation** [comment]
@mikemorgenthaler and @Frenggi What is the expectation here?

**Comment by Frenggi** [comment]
Hi @kyubisation 
For me, the described expected behaviour from @hesyar is correct. That mean, a page number should take the space it needs (expand in width). The fix attribute for the design should be the padding between the page numbers.
And the rule that max. 5 page numbers are displayed should ensure that the whole pagination fits into the viewport.
And I think in this case, the selection circle could be changed to an oval - the same behaviour as for the badge.
