### ISSUE TITLE
Bug: Autocomplete does not close when focus is lost

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#462]
**Describe the bug**
When an autocomlete is focussed and (via JavaScript) another input is focussed, the list stays open.

**To Reproduce**
![focus-lost-autocomplete](https://user-images.githubusercontent.com/117919/85708088-1b988300-b6e4-11ea-8a60-c48000d929f1.gif)

**Expected behavior**
The autocomplete list should close automatically.

**Screenshots**
see above.

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser: Chrome 83
 - Version: SACL-Business 9.7.1

**Comment by kyubisation** [comment]
I don't think we can do this due to technical reasons, as we can not reliably detect this.
What is the use case for this? Can it maybe be solved by manually closing the autocomplete before setting the focus somewhere else?

**Comment by daniel-sc** [comment]
@kyubisation is it not possible to listen on the blur event? But you are right the workaround is possible and not overly complicated (as long as you have the autocomplete trigger at hand..).

**Comment by kyubisation** [comment]
We cannot listen to the blur event, because IE11 fires a blur event when you scroll manually (either the autocomplete content or any container of the input).

**Comment by jeripeierSBB** [comment]
@daniel-sc We could re-evaluate this because we dropped IE support. What do you think?

**Comment by daniel-sc** [comment]
yes, I think this is still relevant.

**Comment by jeripeierSBB** [comment]
As discussed with @daniel-sc and @kyubisation we won't change any behavior regarding this issue at the moment. It's tricky to control blur events correctly, especially because we have a logic implemented which lets stay the overlay open if a user navigates away from the tab and returns to it. Handling every blur event would cause to close the overlay.
A developer has opportunities to control the behavior himself by programmatically closing the overlay.
