### ISSUE TITLE
Bug: ExpressionChangedAfterItHasBeenCheckedError when focus sbb form field on init

### ISSUE THREAD

**Issue by marcodev01** [sbb-design-systems/sbb-angular#757]
**Describe the bug**
We have certain use cases where we programatically set focus to a specific input field on view initialization. The focus is set typically in lifecycle hook ngAfterViewInit. When using a new sbb form field wrapper (sbb-angular v11) it throws a expressionChangedAfterItHasBeenCheckedError. Setting the focus on a input field which is not wrapped by sbb form field is working without throwing any error.

**To Reproduce**
See StackBlitz reproduction - watch console error: https://stackblitz.com/edit/angular-mtbnu6

**Expected behavior**
It should be possible setting focus on an sbb form field without throwing expressionChangedAfterItHasBeenCheckedError

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: all

**Comment by kyubisation** [comment]
This is due to us tracking the focus state of the input. We are unlikely to change this, as this would require a complicated refactoring.
You can work around this, by wrapping the call in a Promise:
`Promise.resolve().then(() => this.myField.nativeElement.focus());`

Be aware that changing state (which includes focus) directly in a `ngAfterViewInit` or `ngAfterContentInit` can often cause ExpressionChangedAfterItHasBeenCheckedError (you will find a lot of results if you search for this online). The workaround with the Promise is the generally accepted variant.

**Comment by marcodev01** [comment]
Thanks for the quick response. 
The down side of the workaround that wraps the call in a Promise or by calling `ChangeDetectorRef` is that it triggers an additional change detection cycle that has a cumulative impact on application performance.
Since there will be no other solution, the workaround should be included in the documentation?
