### ISSUE TITLE
feat(business): notification

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-angular#83]
Design Spec: https://digital.sbb.ch/en/webapps/components/notification

API Spec:

- Selector: sbb-notification
- Inputs:
  - type: 'success' | 'info' | 'warn' | 'error' = 'info'
  - jumpMarks?: JumpMark[]
  - readonly: boolean = false // Prevents notification from being closed

Check reusability with public notification component

```html
<sbb-notification type="success">Saved successfully</sbb-notification>
```

DoD:
- Component implemented
- Documentation provided

**Comment by jgsbb** [comment]
Requirement:
Please allow flexible message with paragraphs instead of one single string message.

**Comment by timschoch** [comment]
Like @jgsbb we need more flexibility too. We currently use a title, text and a link.

**Comment by vlanz** [comment]
@kyubisation I checked the reusability of the public component. Everything would work except for a few new features that would leak over to public as well if implemented, such as the new "warning" type and allowing flexible messages with paragraphs beneath a title.
I imagine since these features are not desired in public, I will create a new business component.
